---
- name: Create Internet gateway
  amazon.aws.ec2_vpc_igw:
    vpc_id: '{{ vpc_id }}'
    state: present
    region: '{{ aws_region }}'
    tags:
      Name: '{{ igw_name }}'
  register: igw
- name: store the gateway id
  set_fact:
    igw_gateway_id: '{{ igw.gateway_id }}'
