---
- name: Set up private subnet route table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: '{{ vpc_id }}'
    region: '{{ aws_region }}'
    tags:
      Name: '{{ priv_rtb }}'
    subnets:
      - "{{ priv_01_subnet_id }}"
      - "{{ priv_02_subnet_id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ nat_gw_id }}"
  register: private_route_table
